project:
  name: "fine_tune_research"

task: "text"

dataset:
  name: "sadmoseby/sample-function-call"
  type: "huggingface"
  task: "text"

base:
  name: "meta-llama/Llama-2-7b-hf"
  type: "huggingface"

output:
  name: "sadmoseby/llama-2-hf-function-call"
  type: "huggingface"

trainer:
  packing: true
  max_seq_length: 512

sft:
  per_device_train_batch_size: 10
  per_device_eval_batch_size: 10
  bf16: true
  learning_rate: 0.0002
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1
  max_steps: 500
  save_strategy: "epoch"
  optim: "paged_adamw_32bit"
  max_grad_norm: 0.3
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  logging_steps: 10

freeze:
  freeze_embed: true
  n_freeze: 24
