project:
  name: "fine_tune_research"

task: "text"

dataset:
  name: "mlabonne/guanaco-llama2-1k"
  type: "huggingface"
  task: "text"

base:
  name: "meta-llama/Llama-2-7b-hf"
  type: "huggingface"

output:
  name: "rparundekar/llama2-7b-guanaco"
  type: "huggingface"

trainer:
  packing: false
  max_seq_length: 512

sft:
  per_device_train_batch_size: 20
  per_device_eval_batch_size: 20
  bf16: true
  learning_rate: 0.0002
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1
  max_steps: 500
  optim: "paged_adamw_32bit"
  max_grad_norm: 0.3
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  logging_strategy: "steps"
  logging_steps: 5

peft:
  r: 64
  lora_alpha: 16
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
